name: BlockDisplays
main: com.hedario.blockdisplays.BlockDisplays
version: ${project.version}
api-version: 1.18
authors: ['Hedario']
commands:
  bd:
    usage: /<command>
    description: BD main command
permissions:
  blockdisplays.command.admin: 
    default: op
    description: Access to all commands.
    children:
      blockdisplays.command.list: true
      blockdisplays.command.create: true
      blockdisplays.command.delete: true
      blockdisplays.command.help: true
      blockdisplays.command.version: true
      blockdisplays.command.reload: true
      blockdisplays.command.teleport: true
      blockdisplays.command.edit: true
      blockdisplays.command.info: true
      